### PR TITLE
Add a docker-compose file and explanation

### PR DESCRIPTION
**Pull request by marcelmaatkamp**
Add a docker-compose.yml which defines Redis, Xcessiv and a shared data directory.

### CODE REVIEW

**Comment by reiinakano** [comment]
Hi @marcelmaatkamp, thanks a lot for this. Using docker-compose is definitely a user-friendly option! One question though:

For the line `command: bash -c "xcessiv -H redis -P 6379"`

Why use bash? Won't `xcessiv -H redis -P 6379` work just as well?

**Comment by marcelmaatkamp** [comment]
It is more out of convenience, the 'command' parameter in docker-compose will bork far too often when specifying environment variables or when using weird escape parameters but in this example it would work just as fine.

**Comment by reiinakano** [comment]
Will take your word for it. You seem like you have more Docker experience. :) 

Thanks for the contribution!

**Comment by marcelmaatkamp** [comment]
And thank you for this awesome library!

**Comment by isaiahakello** [comment]
how can i add this compose  file and set a specific port 80?

**Pull request merged**
